export const messages = {
    de: {
        pages: {
            pages: 'Seiten',
            blocks: 'Blöcke',
            title: 'Titel',
            meta_information: 'Meta Informationen',
            og_information: 'Open Graph Informationen',
            og_title: 'Open Graph Titel',
            og_description: 'Open Graph Beschreibung',
            og_type: 'Open Graph Typ',
            og_image: 'Open Graph Bild',
            og_url: 'Open Graph URL',
            description: 'Beschreibung',
            preview: 'Vorschau',
            page_settings: 'Seiten Einstellungen',
            delete_page: 'Seite löschen',
            confirm_delete_page:
                'Namen der Seite eingeben um das Löschen zu bestätigen',
            page_slug: 'Seiten Slug',
            page_name: 'Seiten Name',
            new_page: 'Neue Seite',
            save: 'Speichern',
            duplicate: 'Duplizieren',
            duplicate_page: 'Seite Duplizieren',
            new_page_name: 'Neuer Seiten Name',
            edit_slug: 'Slug bearbeiten',
            show_all: 'Alle zeigen',
            name: 'Name',
            template: 'Template',
            slug: 'Slug',
            collapse_all: 'Alle einklappen',
            sub_page: 'Unterseite',
            delete: 'Löschen',
            content: 'Inhalt',
            settings: 'Einstellungen',
            versions: 'Versionen',
            planned: 'geplant',
            offline: 'offline',
            online: 'online',
            sections: 'Sektionen',
            help_text:
                'Seiten sind die einzelnen per URL aufrufbaren Seiten der Website. Eine Seite basiert auf einem Template und wird aus einem Pool von frei kombinierbaren Content-Sektionen aufgebaut. Eine Seite verfügt immer über einen Slug, der Teil der URL ist. Seiten können hierarchisch verschachtelt werden, sodass sich die Slugs der verschachtelten Seiten entsprechend zur URL zusammensetzen.',
        },
    },
    en: {
        pages: {
            pages: 'Pages',
            blocks: 'Blocks',
            title: 'Title',
            meta_information: 'Meta Informations',
            og_title: 'Open Graph Title',
            og_description: 'Open Graph Description',
            og_type: 'Open Graph Type',
            og_image: 'Open Graph Image',
            og_url: 'Open Graph URL',
            og_information: 'Open Graph Informations',
            description: 'Description',
            preview: 'Preview',
            page_settings: 'Page Settings',
            delete_page: 'Delete Page',
            page_slug: 'Page Slug',
            page_name: 'Page Name',
            new_page: 'New Page',
            save: 'Save',
            duplicate: 'Duplicate',
            duplicate_page: 'Duplicate Page',
            new_page_name: 'New Page Name',
            show_all: 'Show all',
            edit_slug: 'Edit Slug',
            name: 'Name',
            template: 'Template',
            slug: 'Slug',
            collapse_all: 'Collapse all',
            sub_page: 'Sub Page',
            delete: 'Delete',
            content: 'Content',
            settings: 'Settings',
            versions: 'Versions',
            planned: 'planned',
            offline: 'offline',
            online: 'online',
            sections: 'Sections',
            help_text:
                'Pages are the individual pages of the website that can be called up via URL. A page is based on a template and is built from a pool of freely combinable content sections. A page always has a slug that is part of the URL. Pages can be nested hierarchically, so that the slugs of the nested pages are composed according to the URL.',
        },
    },
};
