export const messages = {
    de: {
        pages: {
            pages: 'Seiten',
            blocks: 'Blöcke',
            meta_information: 'Meta Informationen',
            description: 'Beschreibung',
            preview: 'Vorschau',
            page_settings: 'Seiten Einstellungen',
            delete_page: 'Seite löschen',
            page_slug: 'Seiten Slug',
            page_name: 'Seiten Name',
            new_page: 'Neue Seite',
            save: 'Speichern',
            duplicate: 'Duplizieren',
            duplicate_page: 'Seite Duplizieren',
            new_page_name: 'Neuer Seiten Name',
            edit_slug: 'Slug bearbeiten',
            show_all: 'Alle zeigen',
            collapse_all: 'Alle einklappen',
            sub_page: 'Unterseite',
            delete: 'Löschen',
            content: 'Inhalt',
            settings: 'Einstellungen',
            versions: 'Versionen',
            planned: 'geplant',
        },
    },
    en: {
        pages: {
            pages: 'Pages',
            blocks: 'Blocks',
            meta_information: 'Meta Informations',
            description: 'Description',
            preview: 'Preview',
            page_settings: 'Page Settings',
            delete_page: 'Delete Page',
            page_slug: 'Page Slug',
            page_name: 'Page Name',
            new_page: 'New Page',
            save: 'Save',
            duplicate: 'Duplicate',
            duplicate_page: 'Duplicate Page',
            new_page_name: 'New Page Name',
            edit_slug: 'Edit Slug',
            collapse_all: 'Collapse all',
            sub_page: 'Sub Page',
            delete: 'Delete',
            content: 'Content',
            settings: 'Settings',
            versions: 'Versions',
            planned: 'planned',
        },
    },
};
