export { default as SectionTextFull } from './SectionTextFull.vue';
export { default as SectionTextImage } from './SectionTextImage.vue';
export { default as SectionInfoBox } from './SectionInfoBox.vue';
export { default as SectionImageFull } from './SectionImageFull.vue';
export { default as SectionGridGallery } from './SectionGridGallery.vue';
export { default as SectionCards } from './SectionCards.vue';
export { default as SectionAccordion } from './SectionAccordion.vue';
export { default as SectionLogoWall } from './SectionLogoWall.vue';
export { default as SectionImageCarousel } from './SectionImageCarousel.vue';
