export const messages = {
    de: {
        media: {
            media: 'Medien',
            enter_new_name: 'Neuen Namen eingeben',
            enter_new_key: 'Neuen Key eingeben',
            new_collection: 'Neue Sammlung',
            add_to_collection: 'Zu einer Sammlung hinzufügen',
            clear_selection: 'Auswahl aufheben',
            add: 'Hinzufügen',
            delete: 'Ausgewählte Dateien löschen',
            delete_file: 'Datei löschen',
            images: 'Bilder',
            documents: 'Dokumente',
            all: 'Alle',
            files: 'Dateien',
            selection: 'Auswahl',
            n_files: 'Keine Dateien | Eine Datei | {count} Dateien',
            n_files_selected:
                'Keine Dateien ausgewählt | Eine Datei ausgewählt | {count} Dateien ausgewählt',
            edit_selection: 'Auswahl bearbeiten',
            select_image: 'Bild auswählen',
            select_document: 'Dokument auswählen',
            filter: 'Filter',
            collections: 'Sammlungen',
            collection: 'Sammlung',
            help_text:
                'Medien sind Datei-Uploads. Es werden verschiedene Datei-Formate unterstützt, die in den Content der Website z.B. als Bild oder als PDF-Download, eingebunden werden können. Hochgeladenen Medien können an mehreren Stellen der Website eingebunden und zentral verwaltet werden. Medien können zudem in Collections gruppiert werden.',
        },
    },
    en: {
        media: {
            media: 'Media',
            enter_new_name: 'Enter new name',
            enter_new_key: 'Enter new key',
            new_collection: 'New Collection',
            add_to_collection: 'Add To Collection',
            clear_selection: 'Clear selection',
            add: 'Add',
            delete: 'Delete selected files',
            delete_file: 'Delete file',
            images: 'Images',
            documents: 'Documents',
            all: 'All',
            files: 'Files',
            selection: 'Selection',
            n_files: 'No files | One file | {count} files',
            n_files_selected:
                'No files selected | One file selected | {count} files selected',
            edit_selection: 'Edit Selection',
            select_image: 'Select Image',
            select_document: 'Select Document',
            filter: 'Filter',
            collections: 'Collections',
            collection: 'Collection',
            help_text:
                'Media are file uploads. Various file formats are supported, which can be included in the content of the website, e.g. as an image or as a PDF download. Uploaded media can be included in several places on the website and managed centrally. Media can also be grouped into collections.',
        },
    },
};
